"""empty message

Revision ID: 179da898b33d
Revises: 315c4493f837
Create Date: 2022-08-07 09:54:43.595193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179da898b33d'
down_revision = '315c4493f837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
