"""empty message

Revision ID: 315c4493f837
Revises: c20aa03c9ff7
Create Date: 2022-08-07 09:39:11.324917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315c4493f837'
down_revision = 'c20aa03c9ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('Artist', 'looking_for_talent')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('Venue', 'entity')
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###
