"""empty message

Revision ID: 4a71bd4f6601
Revises: 1dba264e0e95
Create Date: 2022-08-11 13:56:48.202791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a71bd4f6601'
down_revision = '1dba264e0e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_shows')
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_id')
    op.create_table('artist_shows',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shows_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['shows_id'], ['shows.id'], name='artist_shows_shows_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'shows_id', name='artist_shows_pkey')
    )
    # ### end Alembic commands ###
