"""empty message

Revision ID: 7bb710f8b94a
Revises: 8caf87f09d07
Create Date: 2022-08-06 03:35:31.464666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb710f8b94a'
down_revision = '8caf87f09d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
