"""empty message

Revision ID: c20aa03c9ff7
Revises: 7bb710f8b94a
Create Date: 2022-08-07 06:23:55.578491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20aa03c9ff7'
down_revision = '7bb710f8b94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('entity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'entity')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
